# Generated by Django 2.0.3 on 2019-12-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedia', '0003_remove_comment_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.CharField(max_length=60),
        ),
    ]
